// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package trader

import (
	"demo/api/trader"
)

type ControllerV1 struct{}

func NewV1() trader.ITraderV1 {
	return &ControllerV1{}
}
