// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package leaderboard

import (
	"demo/api/leaderboard"
)

type ControllerV1 struct{}

func NewV1() leaderboard.ILeaderboardV1 {
	return &ControllerV1{}
}
