// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: wallet_grpc/v1/wallet.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWalletListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletListReq) Reset() {
	*x = GetWalletListReq{}
	mi := &file_wallet_grpc_v1_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletListReq) ProtoMessage() {}

func (x *GetWalletListReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_grpc_v1_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletListReq.ProtoReflect.Descriptor instead.
func (*GetWalletListReq) Descriptor() ([]byte, []int) {
	return file_wallet_grpc_v1_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *GetWalletListReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetWalletListReq) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

type GetWalletListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*WalletItem          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletListRes) Reset() {
	*x = GetWalletListRes{}
	mi := &file_wallet_grpc_v1_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletListRes) ProtoMessage() {}

func (x *GetWalletListRes) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_grpc_v1_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletListRes.ProtoReflect.Descriptor instead.
func (*GetWalletListRes) Descriptor() ([]byte, []int) {
	return file_wallet_grpc_v1_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletListRes) GetList() []*WalletItem {
	if x != nil {
		return x.List
	}
	return nil
}

type WalletItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address          string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ApiWalletAddress string                 `protobuf:"bytes,3,opt,name=api_wallet_address,json=apiWalletAddress,proto3" json:"api_wallet_address,omitempty"`
	Remark           string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Balance          string                 `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	TotalMarginUsed  string                 `protobuf:"bytes,6,opt,name=total_margin_used,json=totalMarginUsed,proto3" json:"total_margin_used,omitempty"`
	Withdrawable     string                 `protobuf:"bytes,7,opt,name=withdrawable,proto3" json:"withdrawable,omitempty"`
	Upnl             string                 `protobuf:"bytes,8,opt,name=upnl,proto3" json:"upnl,omitempty"`
	DepositWallet    string                 `protobuf:"bytes,9,opt,name=deposit_wallet,json=depositWallet,proto3" json:"deposit_wallet,omitempty"`
	ArbWithdrawAble  string                 `protobuf:"bytes,10,opt,name=arb_withdraw_able,json=arbWithdrawAble,proto3" json:"arb_withdraw_able,omitempty"`
	BscWithdrawAble  string                 `protobuf:"bytes,11,opt,name=bsc_withdraw_able,json=bscWithdrawAble,proto3" json:"bsc_withdraw_able,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WalletItem) Reset() {
	*x = WalletItem{}
	mi := &file_wallet_grpc_v1_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletItem) ProtoMessage() {}

func (x *WalletItem) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_grpc_v1_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletItem.ProtoReflect.Descriptor instead.
func (*WalletItem) Descriptor() ([]byte, []int) {
	return file_wallet_grpc_v1_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *WalletItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WalletItem) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WalletItem) GetApiWalletAddress() string {
	if x != nil {
		return x.ApiWalletAddress
	}
	return ""
}

func (x *WalletItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *WalletItem) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *WalletItem) GetTotalMarginUsed() string {
	if x != nil {
		return x.TotalMarginUsed
	}
	return ""
}

func (x *WalletItem) GetWithdrawable() string {
	if x != nil {
		return x.Withdrawable
	}
	return ""
}

func (x *WalletItem) GetUpnl() string {
	if x != nil {
		return x.Upnl
	}
	return ""
}

func (x *WalletItem) GetDepositWallet() string {
	if x != nil {
		return x.DepositWallet
	}
	return ""
}

func (x *WalletItem) GetArbWithdrawAble() string {
	if x != nil {
		return x.ArbWithdrawAble
	}
	return ""
}

func (x *WalletItem) GetBscWithdrawAble() string {
	if x != nil {
		return x.BscWithdrawAble
	}
	return ""
}

func (x *WalletItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WalletItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_wallet_grpc_v1_wallet_proto protoreflect.FileDescriptor

const file_wallet_grpc_v1_wallet_proto_rawDesc = "" +
	"\n" +
	"\x1bwallet_grpc/v1/wallet.proto\x12\x0ewallet_grpc.v1\"H\n" +
	"\x10GetWalletListReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\"B\n" +
	"\x10GetWalletListRes\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.wallet_grpc.v1.WalletItemR\x04list\"\xb7\x03\n" +
	"\n" +
	"WalletItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12,\n" +
	"\x12api_wallet_address\x18\x03 \x01(\tR\x10apiWalletAddress\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x18\n" +
	"\abalance\x18\x05 \x01(\tR\abalance\x12*\n" +
	"\x11total_margin_used\x18\x06 \x01(\tR\x0ftotalMarginUsed\x12\"\n" +
	"\fwithdrawable\x18\a \x01(\tR\fwithdrawable\x12\x12\n" +
	"\x04upnl\x18\b \x01(\tR\x04upnl\x12%\n" +
	"\x0edeposit_wallet\x18\t \x01(\tR\rdepositWallet\x12*\n" +
	"\x11arb_withdraw_able\x18\n" +
	" \x01(\tR\x0farbWithdrawAble\x12*\n" +
	"\x11bsc_withdraw_able\x18\v \x01(\tR\x0fbscWithdrawAble\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt2d\n" +
	"\rWalletService\x12S\n" +
	"\rGetWalletList\x12 .wallet_grpc.v1.GetWalletListReq\x1a .wallet_grpc.v1.GetWalletListResB\x19Z\x17demo/api/wallet_grpc/v1b\x06proto3"

var (
	file_wallet_grpc_v1_wallet_proto_rawDescOnce sync.Once
	file_wallet_grpc_v1_wallet_proto_rawDescData []byte
)

func file_wallet_grpc_v1_wallet_proto_rawDescGZIP() []byte {
	file_wallet_grpc_v1_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_grpc_v1_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_grpc_v1_wallet_proto_rawDesc), len(file_wallet_grpc_v1_wallet_proto_rawDesc)))
	})
	return file_wallet_grpc_v1_wallet_proto_rawDescData
}

var file_wallet_grpc_v1_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wallet_grpc_v1_wallet_proto_goTypes = []any{
	(*GetWalletListReq)(nil), // 0: wallet_grpc.v1.GetWalletListReq
	(*GetWalletListRes)(nil), // 1: wallet_grpc.v1.GetWalletListRes
	(*WalletItem)(nil),       // 2: wallet_grpc.v1.WalletItem
}
var file_wallet_grpc_v1_wallet_proto_depIdxs = []int32{
	2, // 0: wallet_grpc.v1.GetWalletListRes.list:type_name -> wallet_grpc.v1.WalletItem
	0, // 1: wallet_grpc.v1.WalletService.GetWalletList:input_type -> wallet_grpc.v1.GetWalletListReq
	1, // 2: wallet_grpc.v1.WalletService.GetWalletList:output_type -> wallet_grpc.v1.GetWalletListRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wallet_grpc_v1_wallet_proto_init() }
func file_wallet_grpc_v1_wallet_proto_init() {
	if File_wallet_grpc_v1_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_grpc_v1_wallet_proto_rawDesc), len(file_wallet_grpc_v1_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_grpc_v1_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_grpc_v1_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_grpc_v1_wallet_proto_msgTypes,
	}.Build()
	File_wallet_grpc_v1_wallet_proto = out.File
	file_wallet_grpc_v1_wallet_proto_goTypes = nil
	file_wallet_grpc_v1_wallet_proto_depIdxs = nil
}
