// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package trader_performance

import (
	"demo/api/trader_performance"
)

type ControllerV1 struct{}

func NewV1() trader_performance.ITraderPerformanceV1 {
	return &ControllerV1{}
}
