// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package completed_trades

import (
	"demo/api/completed_trades"
)

type ControllerV1 struct{}

func NewV1() completed_trades.ICompletedTradesV1 {
	return &ControllerV1{}
}
