// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package wallet

import (
	"demo/api/wallet"
)

type ControllerV1 struct{}

func NewV1() wallet.IWalletV1 {
	return &ControllerV1{}
}
