// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package trade

import (
	"demo/api/trade"
)

type ControllerV1 struct{}

func NewV1() trade.ITradeV1 {
	return &ControllerV1{}
}
