// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: copy_trading_grpc/v1/copy_trading.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCopyTradingReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AppId               string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret           string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	CopyTradeConfigId   int64                  `protobuf:"varint,3,opt,name=copy_trade_config_id,json=copyTradeConfigId,proto3" json:"copy_trade_config_id,omitempty"`
	TraderAddress       string                 `protobuf:"bytes,4,opt,name=trader_address,json=traderAddress,proto3" json:"trader_address,omitempty"`
	TraderCoin          string                 `protobuf:"bytes,5,opt,name=trader_coin,json=traderCoin,proto3" json:"trader_coin,omitempty"`
	TraderSzi           float64                `protobuf:"fixed64,6,opt,name=trader_szi,json=traderSzi,proto3" json:"trader_szi,omitempty"`
	TraderLeverageType  string                 `protobuf:"bytes,7,opt,name=trader_leverage_type,json=traderLeverageType,proto3" json:"trader_leverage_type,omitempty"`
	TraderLeverage      int64                  `protobuf:"varint,8,opt,name=trader_leverage,json=traderLeverage,proto3" json:"trader_leverage,omitempty"`
	TraderEntryPx       float64                `protobuf:"fixed64,9,opt,name=trader_entry_px,json=traderEntryPx,proto3" json:"trader_entry_px,omitempty"`
	TraderPositionValue float64                `protobuf:"fixed64,10,opt,name=trader_position_value,json=traderPositionValue,proto3" json:"trader_position_value,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateCopyTradingReq) Reset() {
	*x = CreateCopyTradingReq{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCopyTradingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCopyTradingReq) ProtoMessage() {}

func (x *CreateCopyTradingReq) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCopyTradingReq.ProtoReflect.Descriptor instead.
func (*CreateCopyTradingReq) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCopyTradingReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateCopyTradingReq) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *CreateCopyTradingReq) GetCopyTradeConfigId() int64 {
	if x != nil {
		return x.CopyTradeConfigId
	}
	return 0
}

func (x *CreateCopyTradingReq) GetTraderAddress() string {
	if x != nil {
		return x.TraderAddress
	}
	return ""
}

func (x *CreateCopyTradingReq) GetTraderCoin() string {
	if x != nil {
		return x.TraderCoin
	}
	return ""
}

func (x *CreateCopyTradingReq) GetTraderSzi() float64 {
	if x != nil {
		return x.TraderSzi
	}
	return 0
}

func (x *CreateCopyTradingReq) GetTraderLeverageType() string {
	if x != nil {
		return x.TraderLeverageType
	}
	return ""
}

func (x *CreateCopyTradingReq) GetTraderLeverage() int64 {
	if x != nil {
		return x.TraderLeverage
	}
	return 0
}

func (x *CreateCopyTradingReq) GetTraderEntryPx() float64 {
	if x != nil {
		return x.TraderEntryPx
	}
	return 0
}

func (x *CreateCopyTradingReq) GetTraderPositionValue() float64 {
	if x != nil {
		return x.TraderPositionValue
	}
	return 0
}

type CreateCopyTradingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCopyTradingRes) Reset() {
	*x = CreateCopyTradingRes{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCopyTradingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCopyTradingRes) ProtoMessage() {}

func (x *CreateCopyTradingRes) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCopyTradingRes.ProtoReflect.Descriptor instead.
func (*CreateCopyTradingRes) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCopyTradingRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCopyTradingDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCopyTradingDetailReq) Reset() {
	*x = GetCopyTradingDetailReq{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCopyTradingDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCopyTradingDetailReq) ProtoMessage() {}

func (x *GetCopyTradingDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCopyTradingDetailReq.ProtoReflect.Descriptor instead.
func (*GetCopyTradingDetailReq) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{2}
}

func (x *GetCopyTradingDetailReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetCopyTradingDetailReq) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *GetCopyTradingDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCopyTradingDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CopyTradingItem       `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCopyTradingDetailRes) Reset() {
	*x = GetCopyTradingDetailRes{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCopyTradingDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCopyTradingDetailRes) ProtoMessage() {}

func (x *GetCopyTradingDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCopyTradingDetailRes.ProtoReflect.Descriptor instead.
func (*GetCopyTradingDetailRes) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{3}
}

func (x *GetCopyTradingDetailRes) GetItem() *CopyTradingItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetCopyTradingListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	CopyTradingId int64                  `protobuf:"varint,3,opt,name=copy_trading_id,json=copyTradingId,proto3" json:"copy_trading_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCopyTradingListReq) Reset() {
	*x = GetCopyTradingListReq{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCopyTradingListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCopyTradingListReq) ProtoMessage() {}

func (x *GetCopyTradingListReq) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCopyTradingListReq.ProtoReflect.Descriptor instead.
func (*GetCopyTradingListReq) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{4}
}

func (x *GetCopyTradingListReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetCopyTradingListReq) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *GetCopyTradingListReq) GetCopyTradingId() int64 {
	if x != nil {
		return x.CopyTradingId
	}
	return 0
}

type GetCopyTradingListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CopyTradingItem     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCopyTradingListRes) Reset() {
	*x = GetCopyTradingListRes{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCopyTradingListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCopyTradingListRes) ProtoMessage() {}

func (x *GetCopyTradingListRes) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCopyTradingListRes.ProtoReflect.Descriptor instead.
func (*GetCopyTradingListRes) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{5}
}

func (x *GetCopyTradingListRes) GetList() []*CopyTradingItem {
	if x != nil {
		return x.List
	}
	return nil
}

type SendCopyTradingNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	RefId         int64                  `protobuf:"varint,5,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	RefType       string                 `protobuf:"bytes,6,opt,name=ref_type,json=refType,proto3" json:"ref_type,omitempty"`
	Level         int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCopyTradingNotificationReq) Reset() {
	*x = SendCopyTradingNotificationReq{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCopyTradingNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCopyTradingNotificationReq) ProtoMessage() {}

func (x *SendCopyTradingNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCopyTradingNotificationReq.ProtoReflect.Descriptor instead.
func (*SendCopyTradingNotificationReq) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{6}
}

func (x *SendCopyTradingNotificationReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SendCopyTradingNotificationReq) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *SendCopyTradingNotificationReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendCopyTradingNotificationReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendCopyTradingNotificationReq) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *SendCopyTradingNotificationReq) GetRefType() string {
	if x != nil {
		return x.RefType
	}
	return ""
}

func (x *SendCopyTradingNotificationReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type SendCopyTradingNotificationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCopyTradingNotificationRes) Reset() {
	*x = SendCopyTradingNotificationRes{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCopyTradingNotificationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCopyTradingNotificationRes) ProtoMessage() {}

func (x *SendCopyTradingNotificationRes) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCopyTradingNotificationRes.ProtoReflect.Descriptor instead.
func (*SendCopyTradingNotificationRes) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{7}
}

func (x *SendCopyTradingNotificationRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateCopyTradingStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCopyTradingStatusReq) Reset() {
	*x = UpdateCopyTradingStatusReq{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCopyTradingStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCopyTradingStatusReq) ProtoMessage() {}

func (x *UpdateCopyTradingStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCopyTradingStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateCopyTradingStatusReq) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCopyTradingStatusReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateCopyTradingStatusReq) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *UpdateCopyTradingStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCopyTradingStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateCopyTradingStatusReq) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type UpdateCopyTradingStatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCopyTradingStatusRes) Reset() {
	*x = UpdateCopyTradingStatusRes{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCopyTradingStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCopyTradingStatusRes) ProtoMessage() {}

func (x *UpdateCopyTradingStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCopyTradingStatusRes.ProtoReflect.Descriptor instead.
func (*UpdateCopyTradingStatusRes) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{9}
}

type CopyTradingItem struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Id                             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CopyTradingId                  int64                  `protobuf:"varint,2,opt,name=copy_trading_id,json=copyTradingId,proto3" json:"copy_trading_id,omitempty"`
	UserId                         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetWallet                   string                 `protobuf:"bytes,4,opt,name=target_wallet,json=targetWallet,proto3" json:"target_wallet,omitempty"`
	TargetWalletPlatform           string                 `protobuf:"bytes,5,opt,name=target_wallet_platform,json=targetWalletPlatform,proto3" json:"target_wallet_platform,omitempty"`
	Remark                         string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	FollowType                     int64                  `protobuf:"varint,7,opt,name=follow_type,json=followType,proto3" json:"follow_type,omitempty"`
	FollowOnce                     int64                  `protobuf:"varint,8,opt,name=follow_once,json=followOnce,proto3" json:"follow_once,omitempty"`
	PositionConditions             string                 `protobuf:"bytes,9,opt,name=position_conditions,json=positionConditions,proto3" json:"position_conditions,omitempty"`
	TraderConditions               string                 `protobuf:"bytes,10,opt,name=trader_conditions,json=traderConditions,proto3" json:"trader_conditions,omitempty"`
	TagAccountValue                string                 `protobuf:"bytes,11,opt,name=tag_account_value,json=tagAccountValue,proto3" json:"tag_account_value,omitempty"`
	TagProfitScale                 string                 `protobuf:"bytes,12,opt,name=tag_profit_scale,json=tagProfitScale,proto3" json:"tag_profit_scale,omitempty"`
	TagDirection                   string                 `protobuf:"bytes,13,opt,name=tag_direction,json=tagDirection,proto3" json:"tag_direction,omitempty"`
	TagTradingRhythm               string                 `protobuf:"bytes,14,opt,name=tag_trading_rhythm,json=tagTradingRhythm,proto3" json:"tag_trading_rhythm,omitempty"`
	TagProfitStatus                string                 `protobuf:"bytes,15,opt,name=tag_profit_status,json=tagProfitStatus,proto3" json:"tag_profit_status,omitempty"`
	TagTradingStyles               []string               `protobuf:"bytes,16,rep,name=tag_trading_styles,json=tagTradingStyles,proto3" json:"tag_trading_styles,omitempty"`
	TraderMetricPeriod             string                 `protobuf:"bytes,17,opt,name=trader_metric_period,json=traderMetricPeriod,proto3" json:"trader_metric_period,omitempty"`
	FollowMarginMode               int64                  `protobuf:"varint,18,opt,name=follow_margin_mode,json=followMarginMode,proto3" json:"follow_margin_mode,omitempty"`
	FollowSymbol                   string                 `protobuf:"bytes,19,opt,name=follow_symbol,json=followSymbol,proto3" json:"follow_symbol,omitempty"`
	Leverage                       int64                  `protobuf:"varint,20,opt,name=leverage,proto3" json:"leverage,omitempty"`
	MarginMode                     int64                  `protobuf:"varint,21,opt,name=margin_mode,json=marginMode,proto3" json:"margin_mode,omitempty"`
	FollowModel                    int64                  `protobuf:"varint,22,opt,name=follow_model,json=followModel,proto3" json:"follow_model,omitempty"`
	FollowModelValue               float64                `protobuf:"fixed64,23,opt,name=follow_model_value,json=followModelValue,proto3" json:"follow_model_value,omitempty"`
	MinValue                       float64                `protobuf:"fixed64,24,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue                       float64                `protobuf:"fixed64,25,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	MaxMarginUsage                 float64                `protobuf:"fixed64,26,opt,name=max_margin_usage,json=maxMarginUsage,proto3" json:"max_margin_usage,omitempty"`
	TpValue                        float64                `protobuf:"fixed64,27,opt,name=tp_value,json=tpValue,proto3" json:"tp_value,omitempty"`
	SlValue                        float64                `protobuf:"fixed64,28,opt,name=sl_value,json=slValue,proto3" json:"sl_value,omitempty"`
	OptReverseFollowOrder          int64                  `protobuf:"varint,29,opt,name=opt_reverse_follow_order,json=optReverseFollowOrder,proto3" json:"opt_reverse_follow_order,omitempty"`
	OptFollowupDecrease            int64                  `protobuf:"varint,30,opt,name=opt_followup_decrease,json=optFollowupDecrease,proto3" json:"opt_followup_decrease,omitempty"`
	OptFollowupIncrease            int64                  `protobuf:"varint,31,opt,name=opt_followup_increase,json=optFollowupIncrease,proto3" json:"opt_followup_increase,omitempty"`
	OptForcedLiquidationProtection int64                  `protobuf:"varint,32,opt,name=opt_forced_liquidation_protection,json=optForcedLiquidationProtection,proto3" json:"opt_forced_liquidation_protection,omitempty"`
	OptPositionIncreaseOpening     int64                  `protobuf:"varint,33,opt,name=opt_position_increase_opening,json=optPositionIncreaseOpening,proto3" json:"opt_position_increase_opening,omitempty"`
	OptSlippageProtection          int64                  `protobuf:"varint,34,opt,name=opt_slippage_protection,json=optSlippageProtection,proto3" json:"opt_slippage_protection,omitempty"`
	SymbolListType                 string                 `protobuf:"bytes,35,opt,name=symbol_list_type,json=symbolListType,proto3" json:"symbol_list_type,omitempty"`
	SymbolList                     string                 `protobuf:"bytes,36,opt,name=symbol_list,json=symbolList,proto3" json:"symbol_list,omitempty"`
	MainWallet                     string                 `protobuf:"bytes,37,opt,name=main_wallet,json=mainWallet,proto3" json:"main_wallet,omitempty"`
	MainWalletPlatform             string                 `protobuf:"bytes,38,opt,name=main_wallet_platform,json=mainWalletPlatform,proto3" json:"main_wallet_platform,omitempty"`
	CopyTradingStatus              int64                  `protobuf:"varint,39,opt,name=copy_trading_status,json=copyTradingStatus,proto3" json:"copy_trading_status,omitempty"`
	CopyTradingCreatedAt           string                 `protobuf:"bytes,40,opt,name=copy_trading_created_at,json=copyTradingCreatedAt,proto3" json:"copy_trading_created_at,omitempty"`
	CopyTradingUpdatedAt           string                 `protobuf:"bytes,41,opt,name=copy_trading_updated_at,json=copyTradingUpdatedAt,proto3" json:"copy_trading_updated_at,omitempty"`
	TraderAddress                  string                 `protobuf:"bytes,42,opt,name=trader_address,json=traderAddress,proto3" json:"trader_address,omitempty"`
	TraderCoin                     string                 `protobuf:"bytes,43,opt,name=trader_coin,json=traderCoin,proto3" json:"trader_coin,omitempty"`
	TraderSzi                      float64                `protobuf:"fixed64,44,opt,name=trader_szi,json=traderSzi,proto3" json:"trader_szi,omitempty"`
	TraderLeverageType             string                 `protobuf:"bytes,45,opt,name=trader_leverage_type,json=traderLeverageType,proto3" json:"trader_leverage_type,omitempty"`
	TraderLeverage                 int64                  `protobuf:"varint,46,opt,name=trader_leverage,json=traderLeverage,proto3" json:"trader_leverage,omitempty"`
	TraderEntryPx                  float64                `protobuf:"fixed64,47,opt,name=trader_entry_px,json=traderEntryPx,proto3" json:"trader_entry_px,omitempty"`
	TraderPositionValue            float64                `protobuf:"fixed64,48,opt,name=trader_position_value,json=traderPositionValue,proto3" json:"trader_position_value,omitempty"`
	Status                         string                 `protobuf:"bytes,49,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg                       string                 `protobuf:"bytes,50,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	CreatedAt                      string                 `protobuf:"bytes,51,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                      string                 `protobuf:"bytes,52,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *CopyTradingItem) Reset() {
	*x = CopyTradingItem{}
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyTradingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyTradingItem) ProtoMessage() {}

func (x *CopyTradingItem) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trading_grpc_v1_copy_trading_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyTradingItem.ProtoReflect.Descriptor instead.
func (*CopyTradingItem) Descriptor() ([]byte, []int) {
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP(), []int{10}
}

func (x *CopyTradingItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CopyTradingItem) GetCopyTradingId() int64 {
	if x != nil {
		return x.CopyTradingId
	}
	return 0
}

func (x *CopyTradingItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CopyTradingItem) GetTargetWallet() string {
	if x != nil {
		return x.TargetWallet
	}
	return ""
}

func (x *CopyTradingItem) GetTargetWalletPlatform() string {
	if x != nil {
		return x.TargetWalletPlatform
	}
	return ""
}

func (x *CopyTradingItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CopyTradingItem) GetFollowType() int64 {
	if x != nil {
		return x.FollowType
	}
	return 0
}

func (x *CopyTradingItem) GetFollowOnce() int64 {
	if x != nil {
		return x.FollowOnce
	}
	return 0
}

func (x *CopyTradingItem) GetPositionConditions() string {
	if x != nil {
		return x.PositionConditions
	}
	return ""
}

func (x *CopyTradingItem) GetTraderConditions() string {
	if x != nil {
		return x.TraderConditions
	}
	return ""
}

func (x *CopyTradingItem) GetTagAccountValue() string {
	if x != nil {
		return x.TagAccountValue
	}
	return ""
}

func (x *CopyTradingItem) GetTagProfitScale() string {
	if x != nil {
		return x.TagProfitScale
	}
	return ""
}

func (x *CopyTradingItem) GetTagDirection() string {
	if x != nil {
		return x.TagDirection
	}
	return ""
}

func (x *CopyTradingItem) GetTagTradingRhythm() string {
	if x != nil {
		return x.TagTradingRhythm
	}
	return ""
}

func (x *CopyTradingItem) GetTagProfitStatus() string {
	if x != nil {
		return x.TagProfitStatus
	}
	return ""
}

func (x *CopyTradingItem) GetTagTradingStyles() []string {
	if x != nil {
		return x.TagTradingStyles
	}
	return nil
}

func (x *CopyTradingItem) GetTraderMetricPeriod() string {
	if x != nil {
		return x.TraderMetricPeriod
	}
	return ""
}

func (x *CopyTradingItem) GetFollowMarginMode() int64 {
	if x != nil {
		return x.FollowMarginMode
	}
	return 0
}

func (x *CopyTradingItem) GetFollowSymbol() string {
	if x != nil {
		return x.FollowSymbol
	}
	return ""
}

func (x *CopyTradingItem) GetLeverage() int64 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *CopyTradingItem) GetMarginMode() int64 {
	if x != nil {
		return x.MarginMode
	}
	return 0
}

func (x *CopyTradingItem) GetFollowModel() int64 {
	if x != nil {
		return x.FollowModel
	}
	return 0
}

func (x *CopyTradingItem) GetFollowModelValue() float64 {
	if x != nil {
		return x.FollowModelValue
	}
	return 0
}

func (x *CopyTradingItem) GetMinValue() float64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *CopyTradingItem) GetMaxValue() float64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *CopyTradingItem) GetMaxMarginUsage() float64 {
	if x != nil {
		return x.MaxMarginUsage
	}
	return 0
}

func (x *CopyTradingItem) GetTpValue() float64 {
	if x != nil {
		return x.TpValue
	}
	return 0
}

func (x *CopyTradingItem) GetSlValue() float64 {
	if x != nil {
		return x.SlValue
	}
	return 0
}

func (x *CopyTradingItem) GetOptReverseFollowOrder() int64 {
	if x != nil {
		return x.OptReverseFollowOrder
	}
	return 0
}

func (x *CopyTradingItem) GetOptFollowupDecrease() int64 {
	if x != nil {
		return x.OptFollowupDecrease
	}
	return 0
}

func (x *CopyTradingItem) GetOptFollowupIncrease() int64 {
	if x != nil {
		return x.OptFollowupIncrease
	}
	return 0
}

func (x *CopyTradingItem) GetOptForcedLiquidationProtection() int64 {
	if x != nil {
		return x.OptForcedLiquidationProtection
	}
	return 0
}

func (x *CopyTradingItem) GetOptPositionIncreaseOpening() int64 {
	if x != nil {
		return x.OptPositionIncreaseOpening
	}
	return 0
}

func (x *CopyTradingItem) GetOptSlippageProtection() int64 {
	if x != nil {
		return x.OptSlippageProtection
	}
	return 0
}

func (x *CopyTradingItem) GetSymbolListType() string {
	if x != nil {
		return x.SymbolListType
	}
	return ""
}

func (x *CopyTradingItem) GetSymbolList() string {
	if x != nil {
		return x.SymbolList
	}
	return ""
}

func (x *CopyTradingItem) GetMainWallet() string {
	if x != nil {
		return x.MainWallet
	}
	return ""
}

func (x *CopyTradingItem) GetMainWalletPlatform() string {
	if x != nil {
		return x.MainWalletPlatform
	}
	return ""
}

func (x *CopyTradingItem) GetCopyTradingStatus() int64 {
	if x != nil {
		return x.CopyTradingStatus
	}
	return 0
}

func (x *CopyTradingItem) GetCopyTradingCreatedAt() string {
	if x != nil {
		return x.CopyTradingCreatedAt
	}
	return ""
}

func (x *CopyTradingItem) GetCopyTradingUpdatedAt() string {
	if x != nil {
		return x.CopyTradingUpdatedAt
	}
	return ""
}

func (x *CopyTradingItem) GetTraderAddress() string {
	if x != nil {
		return x.TraderAddress
	}
	return ""
}

func (x *CopyTradingItem) GetTraderCoin() string {
	if x != nil {
		return x.TraderCoin
	}
	return ""
}

func (x *CopyTradingItem) GetTraderSzi() float64 {
	if x != nil {
		return x.TraderSzi
	}
	return 0
}

func (x *CopyTradingItem) GetTraderLeverageType() string {
	if x != nil {
		return x.TraderLeverageType
	}
	return ""
}

func (x *CopyTradingItem) GetTraderLeverage() int64 {
	if x != nil {
		return x.TraderLeverage
	}
	return 0
}

func (x *CopyTradingItem) GetTraderEntryPx() float64 {
	if x != nil {
		return x.TraderEntryPx
	}
	return 0
}

func (x *CopyTradingItem) GetTraderPositionValue() float64 {
	if x != nil {
		return x.TraderPositionValue
	}
	return 0
}

func (x *CopyTradingItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CopyTradingItem) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CopyTradingItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CopyTradingItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_copy_trading_grpc_v1_copy_trading_proto protoreflect.FileDescriptor

const file_copy_trading_grpc_v1_copy_trading_proto_rawDesc = "" +
	"\n" +
	"'copy_trading_grpc/v1/copy_trading.proto\x12\x14copy_trading_grpc.v1\"\x9b\x03\n" +
	"\x14CreateCopyTradingReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\x12/\n" +
	"\x14copy_trade_config_id\x18\x03 \x01(\x03R\x11copyTradeConfigId\x12%\n" +
	"\x0etrader_address\x18\x04 \x01(\tR\rtraderAddress\x12\x1f\n" +
	"\vtrader_coin\x18\x05 \x01(\tR\n" +
	"traderCoin\x12\x1d\n" +
	"\n" +
	"trader_szi\x18\x06 \x01(\x01R\ttraderSzi\x120\n" +
	"\x14trader_leverage_type\x18\a \x01(\tR\x12traderLeverageType\x12'\n" +
	"\x0ftrader_leverage\x18\b \x01(\x03R\x0etraderLeverage\x12&\n" +
	"\x0ftrader_entry_px\x18\t \x01(\x01R\rtraderEntryPx\x122\n" +
	"\x15trader_position_value\x18\n" +
	" \x01(\x01R\x13traderPositionValue\"&\n" +
	"\x14CreateCopyTradingRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"_\n" +
	"\x17GetCopyTradingDetailReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"T\n" +
	"\x17GetCopyTradingDetailRes\x129\n" +
	"\x04item\x18\x01 \x01(\v2%.copy_trading_grpc.v1.CopyTradingItemR\x04item\"u\n" +
	"\x15GetCopyTradingListReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\x12&\n" +
	"\x0fcopy_trading_id\x18\x03 \x01(\x03R\rcopyTradingId\"R\n" +
	"\x15GetCopyTradingListRes\x129\n" +
	"\x04list\x18\x01 \x03(\v2%.copy_trading_grpc.v1.CopyTradingItemR\x04list\"\xce\x01\n" +
	"\x1eSendCopyTradingNotificationReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x15\n" +
	"\x06ref_id\x18\x05 \x01(\x03R\x05refId\x12\x19\n" +
	"\bref_type\x18\x06 \x01(\tR\arefType\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\"0\n" +
	"\x1eSendCopyTradingNotificationRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x97\x01\n" +
	"\x1aUpdateCopyTradingStatusReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\"\x1c\n" +
	"\x1aUpdateCopyTradingStatusRes\"\xd9\x10\n" +
	"\x0fCopyTradingItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0fcopy_trading_id\x18\x02 \x01(\x03R\rcopyTradingId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12#\n" +
	"\rtarget_wallet\x18\x04 \x01(\tR\ftargetWallet\x124\n" +
	"\x16target_wallet_platform\x18\x05 \x01(\tR\x14targetWalletPlatform\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x12\x1f\n" +
	"\vfollow_type\x18\a \x01(\x03R\n" +
	"followType\x12\x1f\n" +
	"\vfollow_once\x18\b \x01(\x03R\n" +
	"followOnce\x12/\n" +
	"\x13position_conditions\x18\t \x01(\tR\x12positionConditions\x12+\n" +
	"\x11trader_conditions\x18\n" +
	" \x01(\tR\x10traderConditions\x12*\n" +
	"\x11tag_account_value\x18\v \x01(\tR\x0ftagAccountValue\x12(\n" +
	"\x10tag_profit_scale\x18\f \x01(\tR\x0etagProfitScale\x12#\n" +
	"\rtag_direction\x18\r \x01(\tR\ftagDirection\x12,\n" +
	"\x12tag_trading_rhythm\x18\x0e \x01(\tR\x10tagTradingRhythm\x12*\n" +
	"\x11tag_profit_status\x18\x0f \x01(\tR\x0ftagProfitStatus\x12,\n" +
	"\x12tag_trading_styles\x18\x10 \x03(\tR\x10tagTradingStyles\x120\n" +
	"\x14trader_metric_period\x18\x11 \x01(\tR\x12traderMetricPeriod\x12,\n" +
	"\x12follow_margin_mode\x18\x12 \x01(\x03R\x10followMarginMode\x12#\n" +
	"\rfollow_symbol\x18\x13 \x01(\tR\ffollowSymbol\x12\x1a\n" +
	"\bleverage\x18\x14 \x01(\x03R\bleverage\x12\x1f\n" +
	"\vmargin_mode\x18\x15 \x01(\x03R\n" +
	"marginMode\x12!\n" +
	"\ffollow_model\x18\x16 \x01(\x03R\vfollowModel\x12,\n" +
	"\x12follow_model_value\x18\x17 \x01(\x01R\x10followModelValue\x12\x1b\n" +
	"\tmin_value\x18\x18 \x01(\x01R\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x19 \x01(\x01R\bmaxValue\x12(\n" +
	"\x10max_margin_usage\x18\x1a \x01(\x01R\x0emaxMarginUsage\x12\x19\n" +
	"\btp_value\x18\x1b \x01(\x01R\atpValue\x12\x19\n" +
	"\bsl_value\x18\x1c \x01(\x01R\aslValue\x127\n" +
	"\x18opt_reverse_follow_order\x18\x1d \x01(\x03R\x15optReverseFollowOrder\x122\n" +
	"\x15opt_followup_decrease\x18\x1e \x01(\x03R\x13optFollowupDecrease\x122\n" +
	"\x15opt_followup_increase\x18\x1f \x01(\x03R\x13optFollowupIncrease\x12I\n" +
	"!opt_forced_liquidation_protection\x18  \x01(\x03R\x1eoptForcedLiquidationProtection\x12A\n" +
	"\x1dopt_position_increase_opening\x18! \x01(\x03R\x1aoptPositionIncreaseOpening\x126\n" +
	"\x17opt_slippage_protection\x18\" \x01(\x03R\x15optSlippageProtection\x12(\n" +
	"\x10symbol_list_type\x18# \x01(\tR\x0esymbolListType\x12\x1f\n" +
	"\vsymbol_list\x18$ \x01(\tR\n" +
	"symbolList\x12\x1f\n" +
	"\vmain_wallet\x18% \x01(\tR\n" +
	"mainWallet\x120\n" +
	"\x14main_wallet_platform\x18& \x01(\tR\x12mainWalletPlatform\x12.\n" +
	"\x13copy_trading_status\x18' \x01(\x03R\x11copyTradingStatus\x125\n" +
	"\x17copy_trading_created_at\x18( \x01(\tR\x14copyTradingCreatedAt\x125\n" +
	"\x17copy_trading_updated_at\x18) \x01(\tR\x14copyTradingUpdatedAt\x12%\n" +
	"\x0etrader_address\x18* \x01(\tR\rtraderAddress\x12\x1f\n" +
	"\vtrader_coin\x18+ \x01(\tR\n" +
	"traderCoin\x12\x1d\n" +
	"\n" +
	"trader_szi\x18, \x01(\x01R\ttraderSzi\x120\n" +
	"\x14trader_leverage_type\x18- \x01(\tR\x12traderLeverageType\x12'\n" +
	"\x0ftrader_leverage\x18. \x01(\x03R\x0etraderLeverage\x12&\n" +
	"\x0ftrader_entry_px\x18/ \x01(\x01R\rtraderEntryPx\x122\n" +
	"\x15trader_position_value\x180 \x01(\x01R\x13traderPositionValue\x12\x16\n" +
	"\x06status\x181 \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x182 \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"created_at\x183 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x184 \x01(\tR\tupdatedAt2\xf2\x04\n" +
	"\x12CopyTradingService\x12k\n" +
	"\x11CreateCopyTrading\x12*.copy_trading_grpc.v1.CreateCopyTradingReq\x1a*.copy_trading_grpc.v1.CreateCopyTradingRes\x12t\n" +
	"\x14GetCopyTradingDetail\x12-.copy_trading_grpc.v1.GetCopyTradingDetailReq\x1a-.copy_trading_grpc.v1.GetCopyTradingDetailRes\x12n\n" +
	"\x12GetCopyTradingList\x12+.copy_trading_grpc.v1.GetCopyTradingListReq\x1a+.copy_trading_grpc.v1.GetCopyTradingListRes\x12\x89\x01\n" +
	"\x1bSendCopyTradingNotification\x124.copy_trading_grpc.v1.SendCopyTradingNotificationReq\x1a4.copy_trading_grpc.v1.SendCopyTradingNotificationRes\x12}\n" +
	"\x17UpdateCopyTradingStatus\x120.copy_trading_grpc.v1.UpdateCopyTradingStatusReq\x1a0.copy_trading_grpc.v1.UpdateCopyTradingStatusResB\x1fZ\x1ddemo/api/copy_trading_grpc/v1b\x06proto3"

var (
	file_copy_trading_grpc_v1_copy_trading_proto_rawDescOnce sync.Once
	file_copy_trading_grpc_v1_copy_trading_proto_rawDescData []byte
)

func file_copy_trading_grpc_v1_copy_trading_proto_rawDescGZIP() []byte {
	file_copy_trading_grpc_v1_copy_trading_proto_rawDescOnce.Do(func() {
		file_copy_trading_grpc_v1_copy_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_copy_trading_grpc_v1_copy_trading_proto_rawDesc), len(file_copy_trading_grpc_v1_copy_trading_proto_rawDesc)))
	})
	return file_copy_trading_grpc_v1_copy_trading_proto_rawDescData
}

var file_copy_trading_grpc_v1_copy_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_copy_trading_grpc_v1_copy_trading_proto_goTypes = []any{
	(*CreateCopyTradingReq)(nil),           // 0: copy_trading_grpc.v1.CreateCopyTradingReq
	(*CreateCopyTradingRes)(nil),           // 1: copy_trading_grpc.v1.CreateCopyTradingRes
	(*GetCopyTradingDetailReq)(nil),        // 2: copy_trading_grpc.v1.GetCopyTradingDetailReq
	(*GetCopyTradingDetailRes)(nil),        // 3: copy_trading_grpc.v1.GetCopyTradingDetailRes
	(*GetCopyTradingListReq)(nil),          // 4: copy_trading_grpc.v1.GetCopyTradingListReq
	(*GetCopyTradingListRes)(nil),          // 5: copy_trading_grpc.v1.GetCopyTradingListRes
	(*SendCopyTradingNotificationReq)(nil), // 6: copy_trading_grpc.v1.SendCopyTradingNotificationReq
	(*SendCopyTradingNotificationRes)(nil), // 7: copy_trading_grpc.v1.SendCopyTradingNotificationRes
	(*UpdateCopyTradingStatusReq)(nil),     // 8: copy_trading_grpc.v1.UpdateCopyTradingStatusReq
	(*UpdateCopyTradingStatusRes)(nil),     // 9: copy_trading_grpc.v1.UpdateCopyTradingStatusRes
	(*CopyTradingItem)(nil),                // 10: copy_trading_grpc.v1.CopyTradingItem
}
var file_copy_trading_grpc_v1_copy_trading_proto_depIdxs = []int32{
	10, // 0: copy_trading_grpc.v1.GetCopyTradingDetailRes.item:type_name -> copy_trading_grpc.v1.CopyTradingItem
	10, // 1: copy_trading_grpc.v1.GetCopyTradingListRes.list:type_name -> copy_trading_grpc.v1.CopyTradingItem
	0,  // 2: copy_trading_grpc.v1.CopyTradingService.CreateCopyTrading:input_type -> copy_trading_grpc.v1.CreateCopyTradingReq
	2,  // 3: copy_trading_grpc.v1.CopyTradingService.GetCopyTradingDetail:input_type -> copy_trading_grpc.v1.GetCopyTradingDetailReq
	4,  // 4: copy_trading_grpc.v1.CopyTradingService.GetCopyTradingList:input_type -> copy_trading_grpc.v1.GetCopyTradingListReq
	6,  // 5: copy_trading_grpc.v1.CopyTradingService.SendCopyTradingNotification:input_type -> copy_trading_grpc.v1.SendCopyTradingNotificationReq
	8,  // 6: copy_trading_grpc.v1.CopyTradingService.UpdateCopyTradingStatus:input_type -> copy_trading_grpc.v1.UpdateCopyTradingStatusReq
	1,  // 7: copy_trading_grpc.v1.CopyTradingService.CreateCopyTrading:output_type -> copy_trading_grpc.v1.CreateCopyTradingRes
	3,  // 8: copy_trading_grpc.v1.CopyTradingService.GetCopyTradingDetail:output_type -> copy_trading_grpc.v1.GetCopyTradingDetailRes
	5,  // 9: copy_trading_grpc.v1.CopyTradingService.GetCopyTradingList:output_type -> copy_trading_grpc.v1.GetCopyTradingListRes
	7,  // 10: copy_trading_grpc.v1.CopyTradingService.SendCopyTradingNotification:output_type -> copy_trading_grpc.v1.SendCopyTradingNotificationRes
	9,  // 11: copy_trading_grpc.v1.CopyTradingService.UpdateCopyTradingStatus:output_type -> copy_trading_grpc.v1.UpdateCopyTradingStatusRes
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_copy_trading_grpc_v1_copy_trading_proto_init() }
func file_copy_trading_grpc_v1_copy_trading_proto_init() {
	if File_copy_trading_grpc_v1_copy_trading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_copy_trading_grpc_v1_copy_trading_proto_rawDesc), len(file_copy_trading_grpc_v1_copy_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_copy_trading_grpc_v1_copy_trading_proto_goTypes,
		DependencyIndexes: file_copy_trading_grpc_v1_copy_trading_proto_depIdxs,
		MessageInfos:      file_copy_trading_grpc_v1_copy_trading_proto_msgTypes,
	}.Build()
	File_copy_trading_grpc_v1_copy_trading_proto = out.File
	file_copy_trading_grpc_v1_copy_trading_proto_goTypes = nil
	file_copy_trading_grpc_v1_copy_trading_proto_depIdxs = nil
}
