// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: copy_trading_grpc/v1/copy_trading.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CopyTradingService_GetAutoCopyTradingList_FullMethodName = "/copy_trading_grpc.v1.CopyTradingService/GetAutoCopyTradingList"
)

// CopyTradingServiceClient is the client API for CopyTradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CopyTradingServiceClient interface {
	GetAutoCopyTradingList(ctx context.Context, in *GetAutoCopyTradingListReq, opts ...grpc.CallOption) (*GetAutoCopyTradingListRes, error)
}

type copyTradingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCopyTradingServiceClient(cc grpc.ClientConnInterface) CopyTradingServiceClient {
	return &copyTradingServiceClient{cc}
}

func (c *copyTradingServiceClient) GetAutoCopyTradingList(ctx context.Context, in *GetAutoCopyTradingListReq, opts ...grpc.CallOption) (*GetAutoCopyTradingListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAutoCopyTradingListRes)
	err := c.cc.Invoke(ctx, CopyTradingService_GetAutoCopyTradingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CopyTradingServiceServer is the server API for CopyTradingService service.
// All implementations must embed UnimplementedCopyTradingServiceServer
// for forward compatibility.
type CopyTradingServiceServer interface {
	GetAutoCopyTradingList(context.Context, *GetAutoCopyTradingListReq) (*GetAutoCopyTradingListRes, error)
	mustEmbedUnimplementedCopyTradingServiceServer()
}

// UnimplementedCopyTradingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCopyTradingServiceServer struct{}

func (UnimplementedCopyTradingServiceServer) GetAutoCopyTradingList(context.Context, *GetAutoCopyTradingListReq) (*GetAutoCopyTradingListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAutoCopyTradingList not implemented")
}
func (UnimplementedCopyTradingServiceServer) mustEmbedUnimplementedCopyTradingServiceServer() {}
func (UnimplementedCopyTradingServiceServer) testEmbeddedByValue()                            {}

// UnsafeCopyTradingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CopyTradingServiceServer will
// result in compilation errors.
type UnsafeCopyTradingServiceServer interface {
	mustEmbedUnimplementedCopyTradingServiceServer()
}

func RegisterCopyTradingServiceServer(s grpc.ServiceRegistrar, srv CopyTradingServiceServer) {
	// If the following call panics, it indicates UnimplementedCopyTradingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CopyTradingService_ServiceDesc, srv)
}

func _CopyTradingService_GetAutoCopyTradingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAutoCopyTradingListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopyTradingServiceServer).GetAutoCopyTradingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopyTradingService_GetAutoCopyTradingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopyTradingServiceServer).GetAutoCopyTradingList(ctx, req.(*GetAutoCopyTradingListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CopyTradingService_ServiceDesc is the grpc.ServiceDesc for CopyTradingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CopyTradingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "copy_trading_grpc.v1.CopyTradingService",
	HandlerType: (*CopyTradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAutoCopyTradingList",
			Handler:    _CopyTradingService_GetAutoCopyTradingList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "copy_trading_grpc/v1/copy_trading.proto",
}
