// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: copy_trading_grpc/v1/copy_trading.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CopyTradingService_CreateCopyTrading_FullMethodName           = "/copy_trading_grpc.v1.CopyTradingService/CreateCopyTrading"
	CopyTradingService_GetCopyTradingDetail_FullMethodName        = "/copy_trading_grpc.v1.CopyTradingService/GetCopyTradingDetail"
	CopyTradingService_GetCopyTradingList_FullMethodName          = "/copy_trading_grpc.v1.CopyTradingService/GetCopyTradingList"
	CopyTradingService_SendCopyTradingNotification_FullMethodName = "/copy_trading_grpc.v1.CopyTradingService/SendCopyTradingNotification"
	CopyTradingService_UpdateCopyTradingStatus_FullMethodName     = "/copy_trading_grpc.v1.CopyTradingService/UpdateCopyTradingStatus"
)

// CopyTradingServiceClient is the client API for CopyTradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CopyTradingServiceClient interface {
	CreateCopyTrading(ctx context.Context, in *CreateCopyTradingReq, opts ...grpc.CallOption) (*CreateCopyTradingRes, error)
	GetCopyTradingDetail(ctx context.Context, in *GetCopyTradingDetailReq, opts ...grpc.CallOption) (*GetCopyTradingDetailRes, error)
	GetCopyTradingList(ctx context.Context, in *GetCopyTradingListReq, opts ...grpc.CallOption) (*GetCopyTradingListRes, error)
	SendCopyTradingNotification(ctx context.Context, in *SendCopyTradingNotificationReq, opts ...grpc.CallOption) (*SendCopyTradingNotificationRes, error)
	UpdateCopyTradingStatus(ctx context.Context, in *UpdateCopyTradingStatusReq, opts ...grpc.CallOption) (*UpdateCopyTradingStatusRes, error)
}

type copyTradingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCopyTradingServiceClient(cc grpc.ClientConnInterface) CopyTradingServiceClient {
	return &copyTradingServiceClient{cc}
}

func (c *copyTradingServiceClient) CreateCopyTrading(ctx context.Context, in *CreateCopyTradingReq, opts ...grpc.CallOption) (*CreateCopyTradingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCopyTradingRes)
	err := c.cc.Invoke(ctx, CopyTradingService_CreateCopyTrading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copyTradingServiceClient) GetCopyTradingDetail(ctx context.Context, in *GetCopyTradingDetailReq, opts ...grpc.CallOption) (*GetCopyTradingDetailRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCopyTradingDetailRes)
	err := c.cc.Invoke(ctx, CopyTradingService_GetCopyTradingDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copyTradingServiceClient) GetCopyTradingList(ctx context.Context, in *GetCopyTradingListReq, opts ...grpc.CallOption) (*GetCopyTradingListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCopyTradingListRes)
	err := c.cc.Invoke(ctx, CopyTradingService_GetCopyTradingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copyTradingServiceClient) SendCopyTradingNotification(ctx context.Context, in *SendCopyTradingNotificationReq, opts ...grpc.CallOption) (*SendCopyTradingNotificationRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCopyTradingNotificationRes)
	err := c.cc.Invoke(ctx, CopyTradingService_SendCopyTradingNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copyTradingServiceClient) UpdateCopyTradingStatus(ctx context.Context, in *UpdateCopyTradingStatusReq, opts ...grpc.CallOption) (*UpdateCopyTradingStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCopyTradingStatusRes)
	err := c.cc.Invoke(ctx, CopyTradingService_UpdateCopyTradingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CopyTradingServiceServer is the server API for CopyTradingService service.
// All implementations must embed UnimplementedCopyTradingServiceServer
// for forward compatibility.
type CopyTradingServiceServer interface {
	CreateCopyTrading(context.Context, *CreateCopyTradingReq) (*CreateCopyTradingRes, error)
	GetCopyTradingDetail(context.Context, *GetCopyTradingDetailReq) (*GetCopyTradingDetailRes, error)
	GetCopyTradingList(context.Context, *GetCopyTradingListReq) (*GetCopyTradingListRes, error)
	SendCopyTradingNotification(context.Context, *SendCopyTradingNotificationReq) (*SendCopyTradingNotificationRes, error)
	UpdateCopyTradingStatus(context.Context, *UpdateCopyTradingStatusReq) (*UpdateCopyTradingStatusRes, error)
	mustEmbedUnimplementedCopyTradingServiceServer()
}

// UnimplementedCopyTradingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCopyTradingServiceServer struct{}

func (UnimplementedCopyTradingServiceServer) CreateCopyTrading(context.Context, *CreateCopyTradingReq) (*CreateCopyTradingRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCopyTrading not implemented")
}
func (UnimplementedCopyTradingServiceServer) GetCopyTradingDetail(context.Context, *GetCopyTradingDetailReq) (*GetCopyTradingDetailRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCopyTradingDetail not implemented")
}
func (UnimplementedCopyTradingServiceServer) GetCopyTradingList(context.Context, *GetCopyTradingListReq) (*GetCopyTradingListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCopyTradingList not implemented")
}
func (UnimplementedCopyTradingServiceServer) SendCopyTradingNotification(context.Context, *SendCopyTradingNotificationReq) (*SendCopyTradingNotificationRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCopyTradingNotification not implemented")
}
func (UnimplementedCopyTradingServiceServer) UpdateCopyTradingStatus(context.Context, *UpdateCopyTradingStatusReq) (*UpdateCopyTradingStatusRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCopyTradingStatus not implemented")
}
func (UnimplementedCopyTradingServiceServer) mustEmbedUnimplementedCopyTradingServiceServer() {}
func (UnimplementedCopyTradingServiceServer) testEmbeddedByValue()                            {}

// UnsafeCopyTradingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CopyTradingServiceServer will
// result in compilation errors.
type UnsafeCopyTradingServiceServer interface {
	mustEmbedUnimplementedCopyTradingServiceServer()
}

func RegisterCopyTradingServiceServer(s grpc.ServiceRegistrar, srv CopyTradingServiceServer) {
	// If the following call panics, it indicates UnimplementedCopyTradingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CopyTradingService_ServiceDesc, srv)
}

func _CopyTradingService_CreateCopyTrading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCopyTradingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopyTradingServiceServer).CreateCopyTrading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopyTradingService_CreateCopyTrading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopyTradingServiceServer).CreateCopyTrading(ctx, req.(*CreateCopyTradingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CopyTradingService_GetCopyTradingDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCopyTradingDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopyTradingServiceServer).GetCopyTradingDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopyTradingService_GetCopyTradingDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopyTradingServiceServer).GetCopyTradingDetail(ctx, req.(*GetCopyTradingDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CopyTradingService_GetCopyTradingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCopyTradingListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopyTradingServiceServer).GetCopyTradingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopyTradingService_GetCopyTradingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopyTradingServiceServer).GetCopyTradingList(ctx, req.(*GetCopyTradingListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CopyTradingService_SendCopyTradingNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCopyTradingNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopyTradingServiceServer).SendCopyTradingNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopyTradingService_SendCopyTradingNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopyTradingServiceServer).SendCopyTradingNotification(ctx, req.(*SendCopyTradingNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CopyTradingService_UpdateCopyTradingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCopyTradingStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopyTradingServiceServer).UpdateCopyTradingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopyTradingService_UpdateCopyTradingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopyTradingServiceServer).UpdateCopyTradingStatus(ctx, req.(*UpdateCopyTradingStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CopyTradingService_ServiceDesc is the grpc.ServiceDesc for CopyTradingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CopyTradingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "copy_trading_grpc.v1.CopyTradingService",
	HandlerType: (*CopyTradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCopyTrading",
			Handler:    _CopyTradingService_CreateCopyTrading_Handler,
		},
		{
			MethodName: "GetCopyTradingDetail",
			Handler:    _CopyTradingService_GetCopyTradingDetail_Handler,
		},
		{
			MethodName: "GetCopyTradingList",
			Handler:    _CopyTradingService_GetCopyTradingList_Handler,
		},
		{
			MethodName: "SendCopyTradingNotification",
			Handler:    _CopyTradingService_SendCopyTradingNotification_Handler,
		},
		{
			MethodName: "UpdateCopyTradingStatus",
			Handler:    _CopyTradingService_UpdateCopyTradingStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "copy_trading_grpc/v1/copy_trading.proto",
}
