// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user_app_key

import (
	"demo/api/user_app_key"
)

type ControllerV1 struct{}

func NewV1() user_app_key.IUserAppKeyV1 {
	return &ControllerV1{}
}
