// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package app_version

import (
	"demo/api/app_version"
)

type ControllerV1 struct{}

func NewV1() app_version.IAppVersionV1 {
	return &ControllerV1{}
}
