// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package cron_task

import (
	"demo/api/cron_task"
)

type ControllerV1 struct{}

func NewV1() cron_task.ICronTaskV1 {
	return &ControllerV1{}
}
