// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package my_track_wallet

import (
	"demo/api/my_track_wallet"
)

type ControllerV1 struct{}

func NewV1() my_track_wallet.IMyTrackWalletV1 {
	return &ControllerV1{}
}
