// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package proxy_pool

import (
	"demo/api/proxy_pool"
)

type ControllerV1 struct{}

func NewV1() proxy_pool.IProxyPoolV1 {
	return &ControllerV1{}
}
