// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// appVersionDao is the data access object for the table app_version.
// You can define custom methods on it to extend its functionality as needed.
type appVersionDao struct {
	*internal.AppVersionDao
}

var (
	// AppVersion is a globally accessible object for table app_version operations.
	AppVersion = appVersionDao{internal.NewAppVersionDao()}
)

// Add your custom methods and functionality below.
