// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// coinMarketDao is the data access object for the table coin_market.
// You can define custom methods on it to extend its functionality as needed.
type coinMarketDao struct {
	*internal.CoinMarketDao
}

var (
	// CoinMarket is a globally accessible object for table coin_market operations.
	CoinMarket = coinMarketDao{internal.NewCoinMarketDao()}
)

// Add your custom methods and functionality below.
