// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// completedTradesDao is the data access object for the table completed_trades.
// You can define custom methods on it to extend its functionality as needed.
type completedTradesDao struct {
	*internal.CompletedTradesDao
}

var (
	// CompletedTrades is a globally accessible object for table completed_trades operations.
	CompletedTrades = completedTradesDao{internal.NewCompletedTradesDao()}
)

// Add your custom methods and functionality below.
