// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// copyTradeRecordDao is the data access object for the table copy_trade_record.
// You can define custom methods on it to extend its functionality as needed.
type copyTradeRecordDao struct {
	*internal.CopyTradeRecordDao
}

var (
	// CopyTradeRecord is a globally accessible object for table copy_trade_record operations.
	CopyTradeRecord = copyTradeRecordDao{internal.NewCopyTradeRecordDao()}
)

// Add your custom methods and functionality below.
