// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// copyTradingDao is the data access object for the table copy_trading.
// You can define custom methods on it to extend its functionality as needed.
type copyTradingDao struct {
	*internal.CopyTradingDao
}

var (
	// CopyTrading is a globally accessible object for table copy_trading operations.
	CopyTrading = copyTradingDao{internal.NewCopyTradingDao()}
)

// Add your custom methods and functionality below.
