// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// copyTradeConfigDao is the data access object for the table copy_trade_config.
// You can define custom methods on it to extend its functionality as needed.
type copyTradeConfigDao struct {
	*internal.CopyTradeConfigDao
}

var (
	// CopyTradeConfig is a globally accessible object for table copy_trade_config operations.
	CopyTradeConfig = copyTradeConfigDao{internal.NewCopyTradeConfigDao()}
)

// Add your custom methods and functionality below.
