// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// cronTaskDao is the data access object for the table cron_task.
// You can define custom methods on it to extend its functionality as needed.
type cronTaskDao struct {
	*internal.CronTaskDao
}

var (
	// CronTask is a globally accessible object for table cron_task operations.
	CronTask = cronTaskDao{internal.NewCronTaskDao()}
)

// Add your custom methods and functionality below.
