// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// fetchFailuresDao is the data access object for the table fetch_failures.
// You can define custom methods on it to extend its functionality as needed.
type fetchFailuresDao struct {
	*internal.FetchFailuresDao
}

var (
	// FetchFailures is a globally accessible object for table fetch_failures operations.
	FetchFailures = fetchFailuresDao{internal.NewFetchFailuresDao()}
)

// Add your custom methods and functionality below.
