// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// fillFetchFailuresDao is the data access object for the table fill_fetch_failures.
// You can define custom methods on it to extend its functionality as needed.
type fillFetchFailuresDao struct {
	*internal.FillFetchFailuresDao
}

var (
	// FillFetchFailures is a globally accessible object for table fill_fetch_failures operations.
	FillFetchFailures = fillFetchFailuresDao{internal.NewFillFetchFailuresDao()}
)

// Add your custom methods and functionality below.
