// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// fillsDao is the data access object for the table fills.
// You can define custom methods on it to extend its functionality as needed.
type fillsDao struct {
	*internal.FillsDao
}

var (
	// Fills is a globally accessible object for table fills operations.
	Fills = fillsDao{internal.NewFillsDao()}
)

// Add your custom methods and functionality below.
