// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// hotCoinDao is the data access object for the table hot_coin.
// You can define custom methods on it to extend its functionality as needed.
type hotCoinDao struct {
	*internal.HotCoinDao
}

var (
	// HotCoin is a globally accessible object for table hot_coin operations.
	HotCoin = hotCoinDao{internal.NewHotCoinDao()}
)

// Add your custom methods and functionality below.
