// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// leaderboardDao is the data access object for the table leaderboard.
// You can define custom methods on it to extend its functionality as needed.
type leaderboardDao struct {
	*internal.LeaderboardDao
}

var (
	// Leaderboard is a globally accessible object for table leaderboard operations.
	Leaderboard = leaderboardDao{internal.NewLeaderboardDao()}
)

// Add your custom methods and functionality below.
