// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// membershipDao is the data access object for the table membership.
// You can define custom methods on it to extend its functionality as needed.
type membershipDao struct {
	*internal.MembershipDao
}

var (
	// Membership is a globally accessible object for table membership operations.
	Membership = membershipDao{internal.NewMembershipDao()}
)

// Add your custom methods and functionality below.
