// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// myTrackWalletDao is the data access object for the table my_track_wallet.
// You can define custom methods on it to extend its functionality as needed.
type myTrackWalletDao struct {
	*internal.MyTrackWalletDao
}

var (
	// MyTrackWallet is a globally accessible object for table my_track_wallet operations.
	MyTrackWallet = myTrackWalletDao{internal.NewMyTrackWalletDao()}
)

// Add your custom methods and functionality below.
