// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// newPositionDao is the data access object for the table new_position.
// You can define custom methods on it to extend its functionality as needed.
type newPositionDao struct {
	*internal.NewPositionDao
}

var (
	// NewPosition is a globally accessible object for table new_position operations.
	NewPosition = newPositionDao{internal.NewNewPositionDao()}
)

// Add your custom methods and functionality below.
