// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// notificationReadDao is the data access object for the table notification_read.
// You can define custom methods on it to extend its functionality as needed.
type notificationReadDao struct {
	*internal.NotificationReadDao
}

var (
	// NotificationRead is a globally accessible object for table notification_read operations.
	NotificationRead = notificationReadDao{internal.NewNotificationReadDao()}
)

// Add your custom methods and functionality below.
