// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// pnlHistoryDao is the data access object for the table pnl_history.
// You can define custom methods on it to extend its functionality as needed.
type pnlHistoryDao struct {
	*internal.PnlHistoryDao
}

var (
	// PnlHistory is a globally accessible object for table pnl_history operations.
	PnlHistory = pnlHistoryDao{internal.NewPnlHistoryDao()}
)

// Add your custom methods and functionality below.
