// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// proxyPoolsDao is the data access object for the table proxy_pools.
// You can define custom methods on it to extend its functionality as needed.
type proxyPoolsDao struct {
	*internal.ProxyPoolsDao
}

var (
	// ProxyPools is a globally accessible object for table proxy_pools operations.
	ProxyPools = proxyPoolsDao{internal.NewProxyPoolsDao()}
)

// Add your custom methods and functionality below.
