// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// proxyPoolDao is the data access object for the table proxy_pool.
// You can define custom methods on it to extend its functionality as needed.
type proxyPoolDao struct {
	*internal.ProxyPoolDao
}

var (
	// ProxyPool is a globally accessible object for table proxy_pool operations.
	ProxyPool = proxyPoolDao{internal.NewProxyPoolDao()}
)

// Add your custom methods and functionality below.
