// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// serverManagementDao is the data access object for the table server_management.
// You can define custom methods on it to extend its functionality as needed.
type serverManagementDao struct {
	*internal.ServerManagementDao
}

var (
	// ServerManagement is a globally accessible object for table server_management operations.
	ServerManagement = serverManagementDao{internal.NewServerManagementDao()}
)

// Add your custom methods and functionality below.
