// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// systemSettingDao is the data access object for the table system_setting.
// You can define custom methods on it to extend its functionality as needed.
type systemSettingDao struct {
	*internal.SystemSettingDao
}

var (
	// SystemSetting is a globally accessible object for table system_setting operations.
	SystemSetting = systemSettingDao{internal.NewSystemSettingDao()}
)

// Add your custom methods and functionality below.
