// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderAccountValuesDao is the data access object for the table trader_account_values.
// You can define custom methods on it to extend its functionality as needed.
type traderAccountValuesDao struct {
	*internal.TraderAccountValuesDao
}

var (
	// TraderAccountValues is a globally accessible object for table trader_account_values operations.
	TraderAccountValues = traderAccountValuesDao{internal.NewTraderAccountValuesDao()}
)

// Add your custom methods and functionality below.
