// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderFundingsDao is the data access object for the table trader_fundings.
// You can define custom methods on it to extend its functionality as needed.
type traderFundingsDao struct {
	*internal.TraderFundingsDao
}

var (
	// TraderFundings is a globally accessible object for table trader_fundings operations.
	TraderFundings = traderFundingsDao{internal.NewTraderFundingsDao()}
)

// Add your custom methods and functionality below.
