// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderAssetPositionsDao is the data access object for the table trader_asset_positions.
// You can define custom methods on it to extend its functionality as needed.
type traderAssetPositionsDao struct {
	*internal.TraderAssetPositionsDao
}

var (
	// TraderAssetPositions is a globally accessible object for table trader_asset_positions operations.
	TraderAssetPositions = traderAssetPositionsDao{internal.NewTraderAssetPositionsDao()}
)

// Add your custom methods and functionality below.
