// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderOrdersDao is the data access object for the table trader_orders.
// You can define custom methods on it to extend its functionality as needed.
type traderOrdersDao struct {
	*internal.TraderOrdersDao
}

var (
	// TraderOrders is a globally accessible object for table trader_orders operations.
	TraderOrders = traderOrdersDao{internal.NewTraderOrdersDao()}
)

// Add your custom methods and functionality below.
