// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderCoinHoldingDao is the data access object for the table trader_coin_holding.
// You can define custom methods on it to extend its functionality as needed.
type traderCoinHoldingDao struct {
	*internal.TraderCoinHoldingDao
}

var (
	// TraderCoinHolding is a globally accessible object for table trader_coin_holding operations.
	TraderCoinHolding = traderCoinHoldingDao{internal.NewTraderCoinHoldingDao()}
)

// Add your custom methods and functionality below.
