// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderPerformancesDao is the data access object for the table trader_performances.
// You can define custom methods on it to extend its functionality as needed.
type traderPerformancesDao struct {
	*internal.TraderPerformancesDao
}

var (
	// TraderPerformances is a globally accessible object for table trader_performances operations.
	TraderPerformances = traderPerformancesDao{internal.NewTraderPerformancesDao()}
)

// Add your custom methods and functionality below.
