// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderPositionsDao is the data access object for the table trader_positions.
// You can define custom methods on it to extend its functionality as needed.
type traderPositionsDao struct {
	*internal.TraderPositionsDao
}

var (
	// TraderPositions is a globally accessible object for table trader_positions operations.
	TraderPositions = traderPositionsDao{internal.NewTraderPositionsDao()}
)

// Add your custom methods and functionality below.
