// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// tradersDao is the data access object for the table traders.
// You can define custom methods on it to extend its functionality as needed.
type tradersDao struct {
	*internal.TradersDao
}

var (
	// Traders is a globally accessible object for table traders operations.
	Traders = tradersDao{internal.NewTradersDao()}
)

// Add your custom methods and functionality below.
