// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderStatisticsDao is the data access object for the table trader_statistics.
// You can define custom methods on it to extend its functionality as needed.
type traderStatisticsDao struct {
	*internal.TraderStatisticsDao
}

var (
	// TraderStatistics is a globally accessible object for table trader_statistics operations.
	TraderStatistics = traderStatisticsDao{internal.NewTraderStatisticsDao()}
)

// Add your custom methods and functionality below.
