// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderFillsDao is the data access object for the table trader_fills.
// You can define custom methods on it to extend its functionality as needed.
type traderFillsDao struct {
	*internal.TraderFillsDao
}

var (
	// TraderFills is a globally accessible object for table trader_fills operations.
	TraderFills = traderFillsDao{internal.NewTraderFillsDao()}
)

// Add your custom methods and functionality below.
