// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// traderPnlHistoriesDao is the data access object for the table trader_pnl_histories.
// You can define custom methods on it to extend its functionality as needed.
type traderPnlHistoriesDao struct {
	*internal.TraderPnlHistoriesDao
}

var (
	// TraderPnlHistories is a globally accessible object for table trader_pnl_histories operations.
	TraderPnlHistories = traderPnlHistoriesDao{internal.NewTraderPnlHistoriesDao()}
)

// Add your custom methods and functionality below.
