// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// userAppKeyDao is the data access object for the table user_app_key.
// You can define custom methods on it to extend its functionality as needed.
type userAppKeyDao struct {
	*internal.UserAppKeyDao
}

var (
	// UserAppKey is a globally accessible object for table user_app_key operations.
	UserAppKey = userAppKeyDao{internal.NewUserAppKeyDao()}
)

// Add your custom methods and functionality below.
