// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// whaleAnchorDao is the data access object for the table whale_anchor.
// You can define custom methods on it to extend its functionality as needed.
type whaleAnchorDao struct {
	*internal.WhaleAnchorDao
}

var (
	// WhaleAnchor is a globally accessible object for table whale_anchor operations.
	WhaleAnchor = whaleAnchorDao{internal.NewWhaleAnchorDao()}
)

// Add your custom methods and functionality below.
