// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package copy_trade_config

import (
	"demo/api/copy_trade_config"
)

type ControllerV1 struct{}

func NewV1() copy_trade_config.ICopyTradeConfigV1 {
	return &ControllerV1{}
}



