// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package trader_positions

import (
	"demo/api/trader_positions"
)

type ControllerV1 struct{}

func NewV1() trader_positions.ITraderPositionsV1 {
	return &ControllerV1{}
}
