// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package copy_trading

import (
	"demo/api/copy_trading"
)

type ControllerV1 struct{}

func NewV1() copy_trading.ICopyTradingV1 {
	return &ControllerV1{}
}
