// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: copy_trade_config_grpc/v1/copy_trade_config.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CopyTradeConfigService_GetAutoCopyTradeConfigList_FullMethodName = "/copy_trade_config_grpc.v1.CopyTradeConfigService/GetAutoCopyTradeConfigList"
)

// CopyTradeConfigServiceClient is the client API for CopyTradeConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CopyTradeConfigServiceClient interface {
	GetAutoCopyTradeConfigList(ctx context.Context, in *GetAutoCopyTradeConfigListReq, opts ...grpc.CallOption) (*GetAutoCopyTradeConfigListRes, error)
}

type copyTradeConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCopyTradeConfigServiceClient(cc grpc.ClientConnInterface) CopyTradeConfigServiceClient {
	return &copyTradeConfigServiceClient{cc}
}

func (c *copyTradeConfigServiceClient) GetAutoCopyTradeConfigList(ctx context.Context, in *GetAutoCopyTradeConfigListReq, opts ...grpc.CallOption) (*GetAutoCopyTradeConfigListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAutoCopyTradeConfigListRes)
	err := c.cc.Invoke(ctx, CopyTradeConfigService_GetAutoCopyTradeConfigList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CopyTradeConfigServiceServer is the server API for CopyTradeConfigService service.
// All implementations must embed UnimplementedCopyTradeConfigServiceServer
// for forward compatibility.
type CopyTradeConfigServiceServer interface {
	GetAutoCopyTradeConfigList(context.Context, *GetAutoCopyTradeConfigListReq) (*GetAutoCopyTradeConfigListRes, error)
	mustEmbedUnimplementedCopyTradeConfigServiceServer()
}

// UnimplementedCopyTradeConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCopyTradeConfigServiceServer struct{}

func (UnimplementedCopyTradeConfigServiceServer) GetAutoCopyTradeConfigList(context.Context, *GetAutoCopyTradeConfigListReq) (*GetAutoCopyTradeConfigListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAutoCopyTradeConfigList not implemented")
}
func (UnimplementedCopyTradeConfigServiceServer) mustEmbedUnimplementedCopyTradeConfigServiceServer() {
}
func (UnimplementedCopyTradeConfigServiceServer) testEmbeddedByValue() {}

// UnsafeCopyTradeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CopyTradeConfigServiceServer will
// result in compilation errors.
type UnsafeCopyTradeConfigServiceServer interface {
	mustEmbedUnimplementedCopyTradeConfigServiceServer()
}

func RegisterCopyTradeConfigServiceServer(s grpc.ServiceRegistrar, srv CopyTradeConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedCopyTradeConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CopyTradeConfigService_ServiceDesc, srv)
}

func _CopyTradeConfigService_GetAutoCopyTradeConfigList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAutoCopyTradeConfigListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopyTradeConfigServiceServer).GetAutoCopyTradeConfigList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CopyTradeConfigService_GetAutoCopyTradeConfigList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopyTradeConfigServiceServer).GetAutoCopyTradeConfigList(ctx, req.(*GetAutoCopyTradeConfigListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CopyTradeConfigService_ServiceDesc is the grpc.ServiceDesc for CopyTradeConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CopyTradeConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "copy_trade_config_grpc.v1.CopyTradeConfigService",
	HandlerType: (*CopyTradeConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAutoCopyTradeConfigList",
			Handler:    _CopyTradeConfigService_GetAutoCopyTradeConfigList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "copy_trade_config_grpc/v1/copy_trade_config.proto",
}
