// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: copy_trade_config_grpc/v1/copy_trade_config.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAutoCopyTradeConfigListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAutoCopyTradeConfigListReq) Reset() {
	*x = GetAutoCopyTradeConfigListReq{}
	mi := &file_copy_trade_config_grpc_v1_copy_trade_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAutoCopyTradeConfigListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAutoCopyTradeConfigListReq) ProtoMessage() {}

func (x *GetAutoCopyTradeConfigListReq) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trade_config_grpc_v1_copy_trade_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAutoCopyTradeConfigListReq.ProtoReflect.Descriptor instead.
func (*GetAutoCopyTradeConfigListReq) Descriptor() ([]byte, []int) {
	return file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetAutoCopyTradeConfigListReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetAutoCopyTradeConfigListReq) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

type GetAutoCopyTradeConfigListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CopyTradeConfigItem     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAutoCopyTradeConfigListRes) Reset() {
	*x = GetAutoCopyTradeConfigListRes{}
	mi := &file_copy_trade_config_grpc_v1_copy_trade_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAutoCopyTradeConfigListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAutoCopyTradeConfigListRes) ProtoMessage() {}

func (x *GetAutoCopyTradeConfigListRes) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trade_config_grpc_v1_copy_trade_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAutoCopyTradeConfigListRes.ProtoReflect.Descriptor instead.
func (*GetAutoCopyTradeConfigListRes) Descriptor() ([]byte, []int) {
	return file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetAutoCopyTradeConfigListRes) GetList() []*CopyTradeConfigItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetAutoCopyTradeConfigListRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CopyTradeConfigItem struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Id                             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetWallet                   string                 `protobuf:"bytes,3,opt,name=target_wallet,json=targetWallet,proto3" json:"target_wallet,omitempty"`
	TargetWalletPlatform           string                 `protobuf:"bytes,4,opt,name=target_wallet_platform,json=targetWalletPlatform,proto3" json:"target_wallet_platform,omitempty"`
	Remark                         string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	FollowType                     int64                  `protobuf:"varint,6,opt,name=follow_type,json=followType,proto3" json:"follow_type,omitempty"`
	FollowOnce                     int64                  `protobuf:"varint,7,opt,name=follow_once,json=followOnce,proto3" json:"follow_once,omitempty"`
	PositionConditions             string                 `protobuf:"bytes,8,opt,name=position_conditions,json=positionConditions,proto3" json:"position_conditions,omitempty"`
	TraderConditions               string                 `protobuf:"bytes,9,opt,name=trader_conditions,json=traderConditions,proto3" json:"trader_conditions,omitempty"`
	TagAccountValue                string                 `protobuf:"bytes,10,opt,name=tag_account_value,json=tagAccountValue,proto3" json:"tag_account_value,omitempty"`
	TagProfitScale                 string                 `protobuf:"bytes,11,opt,name=tag_profit_scale,json=tagProfitScale,proto3" json:"tag_profit_scale,omitempty"`
	TagDirection                   string                 `protobuf:"bytes,12,opt,name=tag_direction,json=tagDirection,proto3" json:"tag_direction,omitempty"`
	TagTradingRhythm               string                 `protobuf:"bytes,13,opt,name=tag_trading_rhythm,json=tagTradingRhythm,proto3" json:"tag_trading_rhythm,omitempty"`
	TagProfitStatus                string                 `protobuf:"bytes,14,opt,name=tag_profit_status,json=tagProfitStatus,proto3" json:"tag_profit_status,omitempty"`
	TagTradingStyles               []string               `protobuf:"bytes,15,rep,name=tag_trading_styles,json=tagTradingStyles,proto3" json:"tag_trading_styles,omitempty"`
	TraderMetricPeriod             string                 `protobuf:"bytes,16,opt,name=trader_metric_period,json=traderMetricPeriod,proto3" json:"trader_metric_period,omitempty"`
	FollowMarginMode               int64                  `protobuf:"varint,17,opt,name=follow_margin_mode,json=followMarginMode,proto3" json:"follow_margin_mode,omitempty"`
	FollowSymbol                   string                 `protobuf:"bytes,18,opt,name=follow_symbol,json=followSymbol,proto3" json:"follow_symbol,omitempty"`
	Leverage                       int64                  `protobuf:"varint,19,opt,name=leverage,proto3" json:"leverage,omitempty"`
	MarginMode                     int64                  `protobuf:"varint,20,opt,name=margin_mode,json=marginMode,proto3" json:"margin_mode,omitempty"`
	FollowModel                    int64                  `protobuf:"varint,21,opt,name=follow_model,json=followModel,proto3" json:"follow_model,omitempty"`
	FollowModelValue               float64                `protobuf:"fixed64,22,opt,name=follow_model_value,json=followModelValue,proto3" json:"follow_model_value,omitempty"`
	MinValue                       float64                `protobuf:"fixed64,23,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue                       float64                `protobuf:"fixed64,24,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	MaxMarginUsage                 float64                `protobuf:"fixed64,25,opt,name=max_margin_usage,json=maxMarginUsage,proto3" json:"max_margin_usage,omitempty"`
	TpValue                        float64                `protobuf:"fixed64,26,opt,name=tp_value,json=tpValue,proto3" json:"tp_value,omitempty"`
	SlValue                        float64                `protobuf:"fixed64,27,opt,name=sl_value,json=slValue,proto3" json:"sl_value,omitempty"`
	OptReverseFollowOrder          int64                  `protobuf:"varint,28,opt,name=opt_reverse_follow_order,json=optReverseFollowOrder,proto3" json:"opt_reverse_follow_order,omitempty"`
	OptFollowupDecrease            int64                  `protobuf:"varint,29,opt,name=opt_followup_decrease,json=optFollowupDecrease,proto3" json:"opt_followup_decrease,omitempty"`
	OptFollowupIncrease            int64                  `protobuf:"varint,30,opt,name=opt_followup_increase,json=optFollowupIncrease,proto3" json:"opt_followup_increase,omitempty"`
	OptForcedLiquidationProtection int64                  `protobuf:"varint,31,opt,name=opt_forced_liquidation_protection,json=optForcedLiquidationProtection,proto3" json:"opt_forced_liquidation_protection,omitempty"`
	OptPositionIncreaseOpening     int64                  `protobuf:"varint,32,opt,name=opt_position_increase_opening,json=optPositionIncreaseOpening,proto3" json:"opt_position_increase_opening,omitempty"`
	OptSlippageProtection          int64                  `protobuf:"varint,33,opt,name=opt_slippage_protection,json=optSlippageProtection,proto3" json:"opt_slippage_protection,omitempty"`
	SymbolListType                 string                 `protobuf:"bytes,34,opt,name=symbol_list_type,json=symbolListType,proto3" json:"symbol_list_type,omitempty"`
	SymbolList                     string                 `protobuf:"bytes,35,opt,name=symbol_list,json=symbolList,proto3" json:"symbol_list,omitempty"`
	MainWallet                     string                 `protobuf:"bytes,36,opt,name=main_wallet,json=mainWallet,proto3" json:"main_wallet,omitempty"`
	MainWalletPlatform             string                 `protobuf:"bytes,37,opt,name=main_wallet_platform,json=mainWalletPlatform,proto3" json:"main_wallet_platform,omitempty"`
	Status                         int64                  `protobuf:"varint,38,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt                      string                 `protobuf:"bytes,39,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                      string                 `protobuf:"bytes,40,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *CopyTradeConfigItem) Reset() {
	*x = CopyTradeConfigItem{}
	mi := &file_copy_trade_config_grpc_v1_copy_trade_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyTradeConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyTradeConfigItem) ProtoMessage() {}

func (x *CopyTradeConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_copy_trade_config_grpc_v1_copy_trade_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyTradeConfigItem.ProtoReflect.Descriptor instead.
func (*CopyTradeConfigItem) Descriptor() ([]byte, []int) {
	return file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDescGZIP(), []int{2}
}

func (x *CopyTradeConfigItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CopyTradeConfigItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CopyTradeConfigItem) GetTargetWallet() string {
	if x != nil {
		return x.TargetWallet
	}
	return ""
}

func (x *CopyTradeConfigItem) GetTargetWalletPlatform() string {
	if x != nil {
		return x.TargetWalletPlatform
	}
	return ""
}

func (x *CopyTradeConfigItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CopyTradeConfigItem) GetFollowType() int64 {
	if x != nil {
		return x.FollowType
	}
	return 0
}

func (x *CopyTradeConfigItem) GetFollowOnce() int64 {
	if x != nil {
		return x.FollowOnce
	}
	return 0
}

func (x *CopyTradeConfigItem) GetPositionConditions() string {
	if x != nil {
		return x.PositionConditions
	}
	return ""
}

func (x *CopyTradeConfigItem) GetTraderConditions() string {
	if x != nil {
		return x.TraderConditions
	}
	return ""
}

func (x *CopyTradeConfigItem) GetTagAccountValue() string {
	if x != nil {
		return x.TagAccountValue
	}
	return ""
}

func (x *CopyTradeConfigItem) GetTagProfitScale() string {
	if x != nil {
		return x.TagProfitScale
	}
	return ""
}

func (x *CopyTradeConfigItem) GetTagDirection() string {
	if x != nil {
		return x.TagDirection
	}
	return ""
}

func (x *CopyTradeConfigItem) GetTagTradingRhythm() string {
	if x != nil {
		return x.TagTradingRhythm
	}
	return ""
}

func (x *CopyTradeConfigItem) GetTagProfitStatus() string {
	if x != nil {
		return x.TagProfitStatus
	}
	return ""
}

func (x *CopyTradeConfigItem) GetTagTradingStyles() []string {
	if x != nil {
		return x.TagTradingStyles
	}
	return nil
}

func (x *CopyTradeConfigItem) GetTraderMetricPeriod() string {
	if x != nil {
		return x.TraderMetricPeriod
	}
	return ""
}

func (x *CopyTradeConfigItem) GetFollowMarginMode() int64 {
	if x != nil {
		return x.FollowMarginMode
	}
	return 0
}

func (x *CopyTradeConfigItem) GetFollowSymbol() string {
	if x != nil {
		return x.FollowSymbol
	}
	return ""
}

func (x *CopyTradeConfigItem) GetLeverage() int64 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *CopyTradeConfigItem) GetMarginMode() int64 {
	if x != nil {
		return x.MarginMode
	}
	return 0
}

func (x *CopyTradeConfigItem) GetFollowModel() int64 {
	if x != nil {
		return x.FollowModel
	}
	return 0
}

func (x *CopyTradeConfigItem) GetFollowModelValue() float64 {
	if x != nil {
		return x.FollowModelValue
	}
	return 0
}

func (x *CopyTradeConfigItem) GetMinValue() float64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *CopyTradeConfigItem) GetMaxValue() float64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *CopyTradeConfigItem) GetMaxMarginUsage() float64 {
	if x != nil {
		return x.MaxMarginUsage
	}
	return 0
}

func (x *CopyTradeConfigItem) GetTpValue() float64 {
	if x != nil {
		return x.TpValue
	}
	return 0
}

func (x *CopyTradeConfigItem) GetSlValue() float64 {
	if x != nil {
		return x.SlValue
	}
	return 0
}

func (x *CopyTradeConfigItem) GetOptReverseFollowOrder() int64 {
	if x != nil {
		return x.OptReverseFollowOrder
	}
	return 0
}

func (x *CopyTradeConfigItem) GetOptFollowupDecrease() int64 {
	if x != nil {
		return x.OptFollowupDecrease
	}
	return 0
}

func (x *CopyTradeConfigItem) GetOptFollowupIncrease() int64 {
	if x != nil {
		return x.OptFollowupIncrease
	}
	return 0
}

func (x *CopyTradeConfigItem) GetOptForcedLiquidationProtection() int64 {
	if x != nil {
		return x.OptForcedLiquidationProtection
	}
	return 0
}

func (x *CopyTradeConfigItem) GetOptPositionIncreaseOpening() int64 {
	if x != nil {
		return x.OptPositionIncreaseOpening
	}
	return 0
}

func (x *CopyTradeConfigItem) GetOptSlippageProtection() int64 {
	if x != nil {
		return x.OptSlippageProtection
	}
	return 0
}

func (x *CopyTradeConfigItem) GetSymbolListType() string {
	if x != nil {
		return x.SymbolListType
	}
	return ""
}

func (x *CopyTradeConfigItem) GetSymbolList() string {
	if x != nil {
		return x.SymbolList
	}
	return ""
}

func (x *CopyTradeConfigItem) GetMainWallet() string {
	if x != nil {
		return x.MainWallet
	}
	return ""
}

func (x *CopyTradeConfigItem) GetMainWalletPlatform() string {
	if x != nil {
		return x.MainWalletPlatform
	}
	return ""
}

func (x *CopyTradeConfigItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CopyTradeConfigItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CopyTradeConfigItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_copy_trade_config_grpc_v1_copy_trade_config_proto protoreflect.FileDescriptor

const file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDesc = "" +
	"\n" +
	"'copy_trade_config_grpc/v1/copy_trade_config.proto\x12\x14copy_trade_config_grpc.v1\"Q\n" +
	"\x19GetAutoCopyTradeConfigListReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\"l\n" +
	"\x19GetAutoCopyTradeConfigListRes\x129\n" +
	"\x04list\x18\x01 \x03(\v2%.copy_trade_config_grpc.v1.CopyTradeConfigItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd8\f\n" +
	"\x0fCopyTradeConfigItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12#\n" +
	"\rtarget_wallet\x18\x03 \x01(\tR\ftargetWallet\x124\n" +
	"\x16target_wallet_platform\x18\x04 \x01(\tR\x14targetWalletPlatform\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x1f\n" +
	"\vfollow_type\x18\x06 \x01(\x03R\n" +
	"followType\x12\x1f\n" +
	"\vfollow_once\x18\a \x01(\x03R\n" +
	"followOnce\x12/\n" +
	"\x13position_conditions\x18\b \x01(\tR\x12positionConditions\x12+\n" +
	"\x11trader_conditions\x18\t \x01(\tR\x10traderConditions\x12*\n" +
	"\x11tag_account_value\x18\n" +
	" \x01(\tR\x0ftagAccountValue\x12(\n" +
	"\x10tag_profit_scale\x18\v \x01(\tR\x0etagProfitScale\x12#\n" +
	"\rtag_direction\x18\f \x01(\tR\ftagDirection\x12,\n" +
	"\x12tag_trading_rhythm\x18\r \x01(\tR\x10tagTradingRhythm\x12*\n" +
	"\x11tag_profit_status\x18\x0e \x01(\tR\x0ftagProfitStatus\x12,\n" +
	"\x12tag_trading_styles\x18\x0f \x03(\tR\x10tagTradingStyles\x120\n" +
	"\x14trader_metric_period\x18\x10 \x01(\tR\x12traderMetricPeriod\x12,\n" +
	"\x12follow_margin_mode\x18\x11 \x01(\x03R\x10followMarginMode\x12#\n" +
	"\rfollow_symbol\x18\x12 \x01(\tR\ffollowSymbol\x12\x1a\n" +
	"\bleverage\x18\x13 \x01(\x03R\bleverage\x12\x1f\n" +
	"\vmargin_mode\x18\x14 \x01(\x03R\n" +
	"marginMode\x12!\n" +
	"\ffollow_model\x18\x15 \x01(\x03R\vfollowModel\x12,\n" +
	"\x12follow_model_value\x18\x16 \x01(\x01R\x10followModelValue\x12\x1b\n" +
	"\tmin_value\x18\x17 \x01(\x01R\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x18 \x01(\x01R\bmaxValue\x12(\n" +
	"\x10max_margin_usage\x18\x19 \x01(\x01R\x0emaxMarginUsage\x12\x19\n" +
	"\btp_value\x18\x1a \x01(\x01R\atpValue\x12\x19\n" +
	"\bsl_value\x18\x1b \x01(\x01R\aslValue\x127\n" +
	"\x18opt_reverse_follow_order\x18\x1c \x01(\x03R\x15optReverseFollowOrder\x122\n" +
	"\x15opt_followup_decrease\x18\x1d \x01(\x03R\x13optFollowupDecrease\x122\n" +
	"\x15opt_followup_increase\x18\x1e \x01(\x03R\x13optFollowupIncrease\x12I\n" +
	"!opt_forced_liquidation_protection\x18\x1f \x01(\x03R\x1eoptForcedLiquidationProtection\x12A\n" +
	"\x1dopt_position_increase_opening\x18  \x01(\x03R\x1aoptPositionIncreaseOpening\x126\n" +
	"\x17opt_slippage_protection\x18! \x01(\x03R\x15optSlippageProtection\x12(\n" +
	"\x10symbol_list_type\x18\" \x01(\tR\x0esymbolListType\x12\x1f\n" +
	"\vsymbol_list\x18# \x01(\tR\n" +
	"symbolList\x12\x1f\n" +
	"\vmain_wallet\x18$ \x01(\tR\n" +
	"mainWallet\x120\n" +
	"\x14main_wallet_platform\x18% \x01(\tR\x12mainWalletPlatform\x12\x16\n" +
	"\x06status\x18& \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18' \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18( \x01(\tR\tupdatedAt2\x90\x01\n" +
	"\x12CopyTradingService\x12z\n" +
	"\x16GetAutoCopyTradeConfigList\x12/.copy_trade_config_grpc.v1.GetAutoCopyTradeConfigListReq\x1a/.copy_trade_config_grpc.v1.GetAutoCopyTradeConfigListResB\x1fZ\x1ddemo/api/copy_trade_config_grpc/v1b\x06proto3"

var (
	file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDescOnce sync.Once
	file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDescData []byte
)

func file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDescGZIP() []byte {
	file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDescOnce.Do(func() {
		file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDesc), len(file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDesc)))
	})
	return file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDescData
}

var file_copy_trade_config_grpc_v1_copy_trade_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_copy_trade_config_grpc_v1_copy_trade_config_proto_goTypes = []any{
	(*GetAutoCopyTradeConfigListReq)(nil), // 0: copy_trade_config_grpc.v1.GetAutoCopyTradeConfigListReq
	(*GetAutoCopyTradeConfigListRes)(nil), // 1: copy_trade_config_grpc.v1.GetAutoCopyTradeConfigListRes
	(*CopyTradeConfigItem)(nil),           // 2: copy_trade_config_grpc.v1.CopyTradeConfigItem
}
var file_copy_trade_config_grpc_v1_copy_trade_config_proto_depIdxs = []int32{
	2, // 0: copy_trade_config_grpc.v1.GetAutoCopyTradeConfigListRes.list:type_name -> copy_trade_config_grpc.v1.CopyTradeConfigItem
	0, // 1: copy_trade_config_grpc.v1.CopyTradingService.GetAutoCopyTradeConfigList:input_type -> copy_trade_config_grpc.v1.GetAutoCopyTradeConfigListReq
	1, // 2: copy_trade_config_grpc.v1.CopyTradingService.GetAutoCopyTradeConfigList:output_type -> copy_trade_config_grpc.v1.GetAutoCopyTradeConfigListRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_copy_trade_config_grpc_v1_copy_trade_config_proto_init() }
func file_copy_trade_config_grpc_v1_copy_trade_config_proto_init() {
	if File_copy_trade_config_grpc_v1_copy_trade_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDesc), len(file_copy_trade_config_grpc_v1_copy_trade_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_copy_trade_config_grpc_v1_copy_trade_config_proto_goTypes,
		DependencyIndexes: file_copy_trade_config_grpc_v1_copy_trade_config_proto_depIdxs,
		MessageInfos:      file_copy_trade_config_grpc_v1_copy_trade_config_proto_msgTypes,
	}.Build()
	File_copy_trade_config_grpc_v1_copy_trade_config_proto = out.File
	file_copy_trade_config_grpc_v1_copy_trade_config_proto_goTypes = nil
	file_copy_trade_config_grpc_v1_copy_trade_config_proto_depIdxs = nil
}

