// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package membership

import (
	"demo/api/membership"
)

type ControllerV1 struct{}

func NewV1() membership.IMembershipV1 {
	return &ControllerV1{}
}
