// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package server_management

import (
	"demo/api/server_management"
)

type ControllerV1 struct{}

func NewV1() server_management.IServerManagementV1 {
	return &ControllerV1{}
}
